default: &default
  adapter: mysql2
  pool: 10

development:
  <<: *default
  database: scroll_development
  username: myuser
  password: myPassword11
  host: localhost

production:
  <<: *default
  database: scroll_development
  username: myuser
  password: myPassword11
  host: localhost

